version: "3.8"

services:
  app:
    build: 
      context: ./frontend
      args:
        - SERVER_PORT=${SERVER_PORT}
        - SERVER_URL=${SERVER_URL}
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_URL=${SERVER_URL}
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      args:
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
